
services:
  mdm-postgres:
    image: postgres:16
    container_name: mdm-postgres
    environment:
      POSTGRES_DB: mdmdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5433:5432"
